DATATYPES AND ATTRIBUTES

In [2]:
# 1. Create a NumPy array arr of integers from 0 to 5 and print its data type. 
import numpy as np
arr = np.arange(6)
print( arr)
print(arr.dtype)

[0 1 2 3 4 5]
int32


In [28]:
# 2. Given a NumPy array arr, check if its data type is float64. 
arr = np.array(6)
if arr.dtype == np.float64:
    print("The array's data type is float64.")
else:
    print("The array's data type is not float64.")


The array's data type is not float64.


In [29]:
# 3. Create a NumPy array arr with a data type of complex128 containing three complex numbers. 
arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)
print( arr)
print(arr.dtype)


[1.+2.j 3.+4.j 5.+6.j]
complex128


In [30]:
# 4. Convert an existing NumPy array arr of integers to float32 data type. 
arr = np.array([1, 2, 3, 4, 5])
arr_float = arr.astype(np.float32)
print(arr_float)
print(arr_float.dtype)


[1. 2. 3. 4. 5.]
float32


In [31]:
# 5. Given a NumPy array arr with float64 data type, convert it to float32 to reduce decimal precision. 
arr = np.array([1.123456789, 2.987654321, 3.1415926535], dtype=np.float64)
arr_float32 = arr.astype(np.float32)
print(arr_float32)
print(arr_float32.dtype)


[1.1234568 2.9876542 3.1415927]
float32


In [32]:
# 6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.
def array_attributes(arr):
    shape = arr.shape     
    size = arr.size       
    dtype = arr.dtype      
    return shape, size, dtype
arr = np.array([[1, 2, 3], [4, 5, 6]])
shape, size, dtype = array_attributes(arr)
print(shape)
print(size)
print(dtype)

(2, 3)
6
int32


In [33]:
# 7. Create a function array_dimension that returns the dimensionality of a NumPy array. 
def array_dimension(arr):
    return arr.ndim 
arr1 = np.array([1, 2, 3])
print(array_dimension(arr1)) 

1


In [34]:
# 8. Design a function item_size_info that returns the item size and total size in bytes of a NumPy array.
def item_size_info(arr):
    item_size = arr.itemsize         
    total_size = arr.nbytes         
    return item_size, total_size
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
item_size, total_size = item_size_info(arr)
print("item size =",item_size)
print("total size =",total_size)

item size = 4
total size = 24


In [26]:
# 9. Create a function array_strides that returns the strides of the given NumPy array. 
import numpy as np
def array_strides(arr):
    return arr.strides
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
strides = array_strides(arr)
print(strides)


(12, 4)


In [35]:
# 10. Design a function shape_stride_relationship that returns the shape and strides of the given array. 
def shape_stride_relationship(arr):
    return arr.shape, arr.strides
arr = np.array([[10, 20, 30], [40, 50, 60]], dtype=np.int32)
shape, strides = shape_stride_relationship(arr)
print(shape)
print(strides)


(2, 3)
(12, 4)


ARRAY CREATION

In [37]:
# 11. Create a function create_zeros_array(n) to return a NumPy array of zeros with n elements. 
def create_zeros_array(n):
    return np.zeros(n)
zeros_array = create_zeros_array(5)
print(zeros_array)


[0. 0. 0. 0. 0.]


In [38]:
# 12. Write a function create_ones_matrix(rows, cols) to create a 2D array filled with ones.
def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))
ones_matrix = create_ones_matrix(3, 4)
print(ones_matrix)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [39]:
# 13. Write a function generate_range_array(start, stop, step) to create a ranged NumPy array
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)
range_array = generate_range_array(0, 10, 2)
print(range_array)

[0 2 4 6 8]


In [40]:
# 14. Design a function generate_linear_space(start, stop, num) for equally spaced values. 
def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)
linear_array = generate_linear_space(0, 1, 5)
print(linear_array)

[0.   0.25 0.5  0.75 1.  ]


In [42]:
# 15. Create a function create_identity_matrix(n) using numpy.eye. 
def create_identity_matrix(n):
    return np.eye(n)
# Example usage:
matrix = create_identity_matrix(4)
print(matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [43]:
# 16. Write a function that converts a Python list into a NumPy array.
def list_to_numpy_array(py_list):
    return np.array(py_list)
my_list = [1, 2, 3, 4, 5]
array = list_to_numpy_array(my_list)
print(array)

[1 2 3 4 5]


In [45]:
# 17. Create a NumPy array and use numpy.view() to create a new view with the same data. 
def create_array_and_view():
    original_array = np.array([10, 20, 30, 40, 50])
    view_array = original_array.view()
    return original_array, view_array
orig, view = create_array_and_view()
print(orig)
print(view)

[10 20 30 40 50]
[10 20 30 40 50]


CONCATENATION AND STACKING

In [49]:
# 18. Write a function to concatenate two NumPy arrays along a specified axis. 
def concatenate_arrays(arr1, arr2, axis=0):
    try:
        result = np.concatenate((arr1, arr2), axis=axis)
        return result
    except ValueError as e:
        print(f"Error: {e}")
        return None
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(concatenate_arrays(a, b, axis=0))
print(concatenate_arrays(a, b, axis=1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [50]:
# 19. Concatenate two arrays with different shapes horizontally using numpy.concatenate. 
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5],
              [6]])
result = np.concatenate((a, b), axis=1)
print(result)

[[1 2 5]
 [3 4 6]]


In [51]:
# 20. Vertically stack multiple arrays from a list using numpy.vstack. 
def vertical_stack_arrays(array_list):
    try:
        return np.vstack(array_list)
    except ValueError as e:
        print(f"Error: {e}")
        return None
a = np.array([[1, 2]])
b = np.array([[3, 4]])
c = np.array([[5, 6]])
result = vertical_stack_arrays([a, b, c])
print(result)

[[1 2]
 [3 4]
 [5 6]]


ARRAY GENERATION

In [53]:
# 21. Write a function to generate an array of integers within a specified range (inclusive) with a step.
def generate_integer_range(start, stop, step=1):
    if step == 0:
        raise ValueError("Step cannot be zero.")
    if (step > 0 and stop < start) or (step < 0 and stop > start):
        return np.array([], dtype=int)
    return np.arange(start, stop + (1 if step > 0 else -1), step)
print(generate_integer_range(1, 10, 2))   
print(generate_integer_range(10, 1, -3))  


[1 3 5 7 9]
[10  7  4  1]


In [55]:
# 22. Generate 10 equally spaced values between 0 and 1 using NumPy. 
values = np.linspace(0, 1, 10)
print(values)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [56]:
# 23. Create 5 logarithmically spaced values between 1 and 1000.
values = np.logspace(start=0, stop=3, num=5)
print(values)

[   1.            5.62341325   31.6227766   177.827941   1000.        ]


PANDAS + NUMPY

In [57]:
# 24. Create a Pandas DataFrame from a NumPy array with 5 rows and 3 columns of random integers (1-100).
import pandas as pd
data = np.random.randint(1, 101, size=(5, 3))
df = pd.DataFrame(data, columns=['A', 'B', 'C'])
print(df)

    A   B   C
0  73  88  66
1  42  73  81
2  60  66  27
3  13  56   3
4  23  53  42


In [60]:
# 25. Write a function to replace all negative values in a specific column with zeros using NumPy. 
def replace_negatives_in_column(arr, column_index):
    if arr.ndim != 2:    
        raise ValueError("Input array must be 2D.")
    if column_index < 0 or column_index >= arr.shape[1]:
        raise IndexError("Column index out of bounds.")
    modified_arr = arr.copy()
    modified_arr[modified_arr[:, column_index] < 0, column_index] = 0
    return modified_arr
arr = np.array([[ 5, -3,  7],
                [-1,  4, -6],
                [ 8, -9, 10]])
result = replace_negatives_in_column(arr, 1)
print(result)


[[ 5  0  7]
 [-1  4 -6]
 [ 8  0 10]]


INDEXING AND SLICING

In [61]:
# 26. Access the 3rd element from the given NumPy array.
arr = np.array([10, 20, 30, 40, 50])
third_element = arr[2]
print(third_element)

30


In [62]:
# 27. Retrieve the element at index (1, 2) from a 2D array. 
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])
element = arr[1, 2]
print(element)

60


In [63]:
# 28. Extract elements greater than 5 using boolean indexing.
arr = np.array([2, 6, 3, 8, 1, 9])
result = arr[arr > 5]
print(result)

[6 8 9]


In [65]:
# 29. Slice elements from index 2 to 5 (inclusive) from a NumPy array.
arr = np.array([10, 20, 30, 40, 50, 60, 70])
sliced = arr[2:6]  
print(sliced)

[30 40 50 60]


In [66]:
# 30. Slice the sub-array [[2, 3], [5, 6]] from a 2D array.
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
sub_array = arr[0:2, 1:3]
print(sub_array)

[[2 3]
 [5 6]]


ADVANCED INDEXING

In [67]:
# 31. Extract elements based on indices from a 2D array.
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])
row_indices = [0, 1, 2]
col_indices = [2, 1, 0]
selected_elements = arr[row_indices, col_indices]
print(selected_elements)

[30 50 70]


In [68]:
# 32. Filter elements greater than a threshold using boolean indexing. 
arr = np.array([4, 10, 2, 15, 7, 3])
threshold = 5
filtered = arr[arr > threshold]
print(filtered)

[10 15  7]


In [71]:
# 33. Extract specific elements from a 3D array using separate index arrays.
arr = np.arange(24).reshape((2, 3, 4))
depth_indices = np.array([0, 1])
row_indices   = np.array([1, 2])
col_indices   = np.array([2, 3])
selected = arr[depth_indices, row_indices, col_indices]
print("3D array:", arr)
print("Selected elements:", selected)

3D array: [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Selected elements: [ 6 23]


In [72]:
# 34. Return elements satisfying two boolean conditions.
arr = np.array([2, 6, 10, 16, 20, 3, 12])
filtered = arr[(arr > 5) & (arr < 15)]
print(filtered)

[ 6 10 12]


In [73]:
# 35. Extract elements from a 2D array using separate row and column index arrays.
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])
row_indices = np.array([0, 1, 2])
col_indices = np.array([2, 1, 0])
result = arr[row_indices, col_indices]
print("Selected elements:", result)

Selected elements: [30 50 70]


BROADCASTING

In [74]:
# 36. Add scalar 5 to every element of an array using broadcasting. 
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
result = arr + 5
print(result)

[[ 6  7  8]
 [ 9 10 11]]


In [75]:
# 37. Multiply each row of a (3, 4) array by corresponding elements of a (1, 3) array. 
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
row_scalars = np.array([[2, 3, 4]])  
result = arr * row_scalars.T
print(result)

[[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


In [76]:
# 38. Add a (1, 4) array to every row of a (4, 3) array using broadcasting. 
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [10, 11, 12]])
add_arr = np.array([[100, 200, 300, 400]])
add_arr_reshaped = add_arr.T  
result = arr + add_arr_reshaped
print(result)

[[101 102 103]
 [204 205 206]
 [307 308 309]
 [410 411 412]]


In [77]:
# 39. Add two arrays of shapes (3, 1) and (1, 3) using broadcasting.
a = np.array([[1],
              [2],
              [3]])
b = np.array([[10, 20, 30]])
result = a + b
print(result)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [79]:
# 40. Handle shape incompatibility during multiplication between (2, 3) and (2, 2) arrays. 
a = np.array([[1, 2, 3],
              [4, 5, 6]]) 
b = np.array([[7, 8],
            [9, 10],
            [11, 12]])
result = np.dot(a, b)
print(result)            

[[ 58  64]
 [139 154]]


AGGREGATIONS AND STATICS

In [81]:
# 41. Calculate column-wise mean of a 2D array. 
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
column_mean = np.mean(arr, axis=0)
print("Column-wise mean:", column_mean)

Column-wise mean: [4. 5. 6.]


In [82]:
# 42. Find maximum value in each row.
arr = np.array([[3, 7, 1],
                [9, 2, 5],
                [6, 4, 8]])
row_max = np.max(arr, axis=1)
print("Maximum value in each row:", row_max)

Maximum value in each row: [7 9 8]


In [83]:
# 43. Find indices of maximum values in each column. 
arr = np.array([[3, 7, 1],
                [9, 2, 5],
                [6, 4, 8]])
column_max_indices = np.argmax(arr, axis=0)
print("Indices of max values in each column:", column_max_indices)

Indices of max values in each column: [1 0 2]


In [84]:
# 44. Apply a custom function to compute moving sum along rows. 
def moving_sum_rows(arr, window_size):
    rows, cols = arr.shape
    result = []
    for row in arr:
        if cols < window_size:
            result.append([])
        else:
            row_sums = [np.sum(row[i:i+window_size]) for i in range(cols - window_size + 1)]
            result.append(row_sums)
    return np.array(result)
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])
output = moving_sum_rows(arr, window_size=2)
print(output)

[[ 3  5  7]
 [11 13 15]]


In [86]:
# 45. Check if all elements in each column are even.
arr = np.array([[2, 4, 6],
                [8, 5, 10],
                [12, 8, 14]])
all_even_columns = np.all(arr % 2 == 0, axis=0)
print( all_even_columns)

[ True False  True]


RESHAPING AND FLATTENING

In [87]:
# 46. Reshape a given array into dimensions m x n.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
reshaped = arr.reshape(3, 4)
print(reshaped)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [88]:
# 47. Return a flattened version of a given matrix.
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
flat_arr = arr.flatten()
print(flat_arr)

[1 2 3 4 5 6]


In [89]:
# 48. Concatenate two arrays along a specified axis.
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])
result = np.concatenate((a, b), axis=0)
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [91]:
# 49. Split an array into sub-arrays along a specified axis.
arr = np.array([[1, 2],
                [3, 4],
                [5, 6],
                [7, 8]])
split_arrays = np.split(arr, 2, axis=0)
for i, sub in enumerate(split_arrays):
    print(sub)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [92]:
# 50. Insert and delete elements at specified indices from an array. 
arr = np.array([10, 20, 30, 40])
inserted = np.insert(arr, 2, 25)
print("After insertion:", inserted)

After insertion: [10 20 25 30 40]


ELEMENT WISE OPERATIONS

In [93]:
# 51. Perform element-wise addition between two arrays. 
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = a + b  
print("Result:", result)

Result: [5 7 9]


In [94]:
# 52. Perform element-wise subtraction: subtract arr2 from arr1.
arr1 = np.array([10, 20, 30])
arr2 = np.array([1, 2, 3])
result = arr1 - arr2 
print("Result:", result)

Result: [ 9 18 27]


In [95]:
# 53. Perform element-wise multiplication. 
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = a * b  
print("Result:", result)

Result: [ 4 10 18]


In [96]:
# 54. Divide elements of arr1 by arr2 element-wise. 
arr1 = np.array([10, 20, 30])
arr2 = np.array([2, 4, 5])
result = arr1 / arr2  
print("Result:", result)

Result: [5. 5. 6.]


In [97]:
# 55. Perform element-wise exponentiation: arr1 ** arr2.
arr1 = np.array([2, 3, 4])
arr2 = np.array([3, 2, 1])
result = arr1 ** arr2 
print("Result:", result)

Result: [8 9 4]


STRING OPERATIONS

In [98]:
# 56. Count occurrences of a substring in a string array.
arr = np.array(['apple pie', 'banana pie', 'apple tart', 'grape'])
counts = np.char.count(arr, 'apple')
print("Counts:", counts)

Counts: [1 0 1 0]


In [107]:
# 57. Extract uppercase characters from a string array. 
arr = np.array(['Hello World', 'NUMPy Library', 'OpenAI ChatGPT'])
uppercase_chars = np.array([[char for char in string if char.isupper()] for string in arr])
print(uppercase_chars)

In [108]:
# 58. Replace substring occurrences with another string in a string array. 
arr = np.array(['I like apples', 'Apples are tasty', 'Green apples are sour'])
result = np.char.replace(arr, 'apples', 'bananas')
print(result)

['I like bananas' 'Apples are tasty' 'Green bananas are sour']


In [109]:
# 59. Concatenate strings in a NumPy array element-wise. 
arr1 = np.array(['Hello', 'Good', 'Open'])
arr2 = np.array(['World', 'Morning', 'AI'])
result = np.char.add(arr1, arr2)
print(result)

['HelloWorld' 'GoodMorning' 'OpenAI']


In [110]:
# 60. Find the length of the longest string in a string array.
arr = np.array(['apple', 'banana', 'pineapple', 'kiwi'])
lengths = np.char.str_len(arr)
max_length = np.max(lengths)
print("Longest string length:", max_length)

Longest string length: 9


DESCRIPTIVE STATISTICS

In [111]:
# 61. Generate 100 random integers (1–1000) and compute mean, median, variance, and std deviation. 
arr = np.random.randint(1, 1001, size=100)
mean_val = np.mean(arr)
median_val = np.median(arr)
variance_val = np.var(arr)
std_dev_val = np.std(arr)
print("Generated Array:", arr)
print("Mean:", mean_val)
print("Median:", median_val)
print("Variance:", variance_val)
print("Standard Deviation:", std_dev_val)


Generated Array: [499 366 164 110  64 999 114 549 707 983  31 871 326 758 473 805  91 285
 126 437 799 874  74 712 655 530 163 474 982 728 401 275 593 428 843 890
   5 834 113 279 560 345 373 441  76  45 353 854 571 557 284 887 110   8
 522 196 100 173 530 971  48 778 802 748 517 867 507 313 844 156 339 675
 936 243   5 601  89 519 413 347 479 640  84 487 248 626 872 112 990 254
 278 407 958 278 932 734 303 684 539 170]
Mean: 471.88
Median: 473.5
Variance: 87296.20559999999
Standard Deviation: 295.4593129349623


In [112]:
# 62. Generate 50 random numbers (1–100) and compute the 25th and 75th percentiles.
arr = np.random.randint(1, 101, size=50)
percentile_25 = np.percentile(arr, 25)
percentile_75 = np.percentile(arr, 75)
print("Generated Array:", arr)
print("25th Percentile:", percentile_25)
print("75th Percentile:", percentile_75)

Generated Array: [  8  28  50  79  73  93  42 100   2  27  42  96  17   3  78  68  81   8
  25  52  79  34  86  33  89   4  69  19   5  82  82  96  14  36  92  56
  26  39  38  29   1  55   7  24  51  65  24  62  49  70]
25th Percentile: 24.25
75th Percentile: 76.75


In [113]:
# 63. Compute correlation coefficient between two arrays using np.corrcoef. 
x = np.array([10, 20, 30, 40, 50])
y = np.array([15, 25, 35, 45, 60])
corr_matrix = np.corrcoef(x, y)
corr_coef = corr_matrix[0, 1]
print("Correlation coefficient matrix:\n", corr_matrix)
print("Correlation coefficient between x and y:", corr_coef)

Correlation coefficient matrix:
 [[1.         0.99589321]
 [0.99589321 1.        ]]
Correlation coefficient between x and y: 0.995893206467704


In [114]:
# 64. Perform matrix multiplication using np.dot.
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])
result = np.dot(A, B)
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Result of A · B:\n", result)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Result of A · B:
 [[19 22]
 [43 50]]


In [117]:
# 65. Compute the 10th, 50th, and 90th percentiles and quartiles for an array of 50 integers. 
arr = np.random.randint(1, 101, size=50)
p10 = np.percentile(arr, 10)
p50 = np.percentile(arr, 50) 
p90 = np.percentile(arr, 90)
q1 = np.percentile(arr, 25)
q2 = np.percentile(arr, 50)  
q3 = np.percentile(arr, 75)

print("Array:", arr)
print("10th Percentile:", p10)
print("50th Percentile (Median):", p50)
print("90th Percentile:", p90)
print("Q1 (25th percentile):", q1)
print("Q2 (50th percentile - Median):", q2)
print("Q3 (75th percentile):", q3)


Array: [59 97 67 22 75 51 84 99 59 78 13 46 21 82 41 16 35 72  6 18  9 50 91 64
 32 86 53 26 65  4 99 85 27 40 95 77 18 75 81  8 68 99  7 83 56  4  7 66
 31 46]
10th Percentile: 7.9
50th Percentile (Median): 54.5
90th Percentile: 91.4
Q1 (25th percentile): 23.0
Q2 (50th percentile - Median): 54.5
Q3 (75th percentile): 77.75


SEARCH AND SORT

In [118]:
# 66. Find index of a specific element in an array. 
arr = np.array([10, 20, 30, 40, 50, 30])
index = np.where(arr == 30)
print("Indices of 30:", index[0])

Indices of 30: [2 5]


In [119]:
# 67. Sort a random array in ascending order.
arr = np.random.randint(1, 101, size=10) 
sorted_arr = np.sort(arr)
print("Original Array:", arr)
print("Sorted Array (Ascending):", sorted_arr)

Original Array: [84 79  5 12 83 72 10 64 36 41]
Sorted Array (Ascending): [ 5 10 12 36 41 64 72 79 83 84]


In [120]:
# 68. Filter elements greater than 20.
arr = np.random.randint(1, 51, size=15)
filtered_arr = arr[arr > 20]
print("Original Array:", arr)
print("Filtered Array (Elements > 20):", filtered_arr)

Original Array: [21 43  5 49 30 25  5 50 36  2  9 10 28  3 32]
Filtered Array (Elements > 20): [21 43 49 30 25 50 36 28 32]


In [121]:
# 69. Filter elements divisible by 3. 
arr = np.random.randint(1, 101, size=15)  
filtered_arr = arr[arr % 3 == 0]
print("Original Array:", arr)
print("Filtered Array (Divisible by 3):", filtered_arr)

Original Array: [61  9 86 23 19 44 61 58 49 95 49 95 77 81 85]
Filtered Array (Divisible by 3): [ 9 81]


In [122]:
# 70. Filter elements between 20 and 40 (inclusive). 
arr = np.random.randint(1, 101, size=15)  
filtered_arr = arr[(arr >= 20) & (arr <= 40)]
print("Original Array:", arr)
print("Filtered Array (20 to 40 inclusive):", filtered_arr)

Original Array: [30 67 92 14 58 21 48 56 37  4 19 24 30 75 61]
Filtered Array (20 to 40 inclusive): [30 21 37 24 30]


BYTE ORDER AND SWAPPING

In [123]:
# 71. Check byte order of a NumPy array using dtype.byteorder. 
arr = np.array([1, 2, 3], dtype=np.int16)
byte_order = arr.dtype.byteorder
print("Array:", arr)
print("Byte order:", byte_order)

Array: [1 2 3]
Byte order: =


In [124]:
# 72. Perform in-place byte swapping using byteswap().
arr = np.array([1, 256, 1024], dtype=np.int16)
print("Original array:", arr)
print("Original byte order:", arr.dtype.byteorder)
arr.byteswap(inplace=True)
print("Array after byte swap:", arr)
print("Byte order after swap:", arr.dtype.byteorder)

Original array: [   1  256 1024]
Original byte order: =
Array after byte swap: [256   1   4]
Byte order after swap: =
